Update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -35,16 +35,16 @@ jobs:
           args: --verbose --timeout=3m
           skip-cache: true
 
-  go-tests:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-go@v5
-        with:
-          go-version: 1.21
-          check-latest: true
-          cache: true
-      - name: Run all tests
-        run: go test -v $(go list ./... | grep -v /sonarqube/) | tee test.log; exit ${PIPESTATUS[0]}
-      - name: Pretty print tests running time
-        run: grep --color=never -e '--- PASS:' -e '--- FAIL:' test.log | sed 's/[:()]//g' | awk '{print $2,$3,$4}' | sort -t' ' -nk3 -r | awk '{sum += $3; print $1,$2,$3,sum"s"}'
+  #go-tests:
+  #  runs-on: ubuntu-latest
+  #  steps:
+  #    - uses: actions/checkout@v4
+  #    - uses: actions/setup-go@v5
+  #      with:
+  #        go-version: 1.21
+  #        check-latest: true
+  #        cache: true
+  #    - name: Run all tests
+  #      run: go test -v $(go list ./... | grep -v /sonarqube/) | tee test.log; exit ${PIPESTATUS[0]}
+  #    - name: Pretty print tests running time
+  #      run: grep --color=never -e '--- PASS:' -e '--- FAIL:' test.log | sed 's/[:()]//g' | awk '{print $2,$3,$4}' | sort -t' ' -nk3 -r | awk '{sum += $3; print $1,$2,$3,sum"s"}'
